"use client";

import Sorting from "../components/Sorting";

export default function PaladinPage() {
  return (
    <Sorting
      class="Paladin"
      zoneOneRaceOne="Elwynn Forest"
      zoneOneRaceTwo="Dun Morogh"
      zoneTwoRaceOne="Westfall"
      zoneTwoRaceTwo="Loch Modan"
      zoneOneCityRaceOne="Stormwind City"
      zoneOneCityRaceTwo="Stormwind City"
      infoStarterZoneFirstRune="Once you're strong enough to learn new abilities, go have a word with your trainer for the first time! They might have something to show you."
      infoStarterZoneSecondRuneRaceOne="Where spiders roam in caves, adventurers have been known to become poisoned and diseased. Find a Wounded Aventurer and Purify them, and they may teach you something new in return."
      infoStarterZoneSecondRuneRaceTwo="Where leprosy roams near a former city, adventurers have been known to become poisoned and diseased. Find a Wounded Aventurer and Purify them, and they may teach you something new in return."
      infoStarterZoneThirdRuneRaceOne="East of the southern docks where smuggling is known to occur, a fallen adventurer restlessly awaits their last rites. Bring a healing friend and give these to the corpse to receive its knowledge."
      infoStarterZoneThirdRuneRaceTwo="Down the hills and to the west of Kharanos, a cave of wendigo's sits. Inside, a fallen adventurer restlessly awaits their last rites. Bring a healing friend and give these to the corpse to receive its knowledge."
      infoSecondZoneFirstRuneRaceOne="A wicked, undead member of the Defias is rumored to lurk near the southeastern border to Duskwood. Defeat them and claim the Libram they carry to unlock new powers."
      infoSecondZoneSecondRuneRaceOne="Inside the northern and western Defias mines, an eternal skeletal worker has appeared carrying a Libram of power. Defeat them with holy power to reclaim it."
      infoSecondZoneFirstRuneRaceTwo="Inside a cave filled with Troggs, a reliquary is rumored to have sunk beneath the pools. Inside, a Libram is said to contain great power if its contents can be deciphered."
      infoSecondZoneSecondRuneRaceTwo="A retinue of paladins recently passed through Thelsamar and spent a night at the inn. When they left, a Libram remained in one of the lower rooms, only reclaimable by a paladin."
      infoCitiesRaceOne="Inside the city of Stormwind, within the Park, a local bartender has a position for a bouncer available, with the promise of a reward if one accepts the role."
      infoCitiesRaceTwo="Inside the city of Stormwind, within the Park, a local bartender has a position for a bouncer available, with the promise of a reward if one accepts the role."
      infoCitiesTwoRaceOne="A member of the Stormwind Cathedral has gone missing and has left no word of their location. Investigate the catacombs beneath the church for a clue to where she might be."
      infoCitiesTwoRaceTwo="A member of the Stormwind Cathedral has gone missing and has left no word of their location. Investigate the catacombs beneath the church for a clue to where she might be."
      infoMiscZoneOne="Throughout the red mountains near Elwynn Forest, a Blasphemous orc has been known to spread his vile taint. Defeat him to learn this ability."
      infoMiscZoneTwo="Upon defeating foes, you may stumble upon unfinished crates that can be returned to the Azeroth Commerce Authority either empty or filled with goods. Become Friends with these people and they may reveal some new skills to you."
      infoMiscZoneThree="A goblin in Ratchet has hoarded a great many runes, and he has one for you as well. In order to retrieve it, you must complete the tasks he gives you, and provide to him the items he seeks."
      infoMiscZoneFour="There is a dangerous tower hidden away in Darkshore, where foul warlocks gather to cast powerful magic. These warlocks possess an orb of great evil. Claim it, and find a purifier along the road to Ashenvale that might help you quell the evil magic within. Follow his instructions and once you turn to the Warlocks of Stormwind for assistance, travel to the site of Mannoroth's destruction and slay the demons there until you have enough essence to destroy the orb upon his fallen weapons."
      infoMiscZoneFiveRaceOne="In the wicked forests of Duskwood, the Defias Brotherhood have gathered up holy librams for their nefarious purposes. Reclaim one from them and follow its instructions to unlock the power within."
      infoMiscZoneFiveRaceTwo="In the wicked forests of Duskwood, the Defias Brotherhood have gathered up holy librams for their nefarious purposes. Reclaim one from them and follow its instructions to unlock the power within."
      runeOne="Aegis"
      runeTwo="Avenger's Shield"
      runeThree="Beacon of Light"
      runeFour="Crusader Strike"
      runeFive="Divine Sacrifice"
      runeSix="Divine Storm"
      runeSeven="Exorcist"
      runeEight="Hand of Reckoning"
      runeNine="Horn of Lordaeron"
      runeTen="Inspiration Exemplar"
      runeEleven="Rebuke"
      runeTwelve="Seal of Martyrdom"
      runeOneRumorRaceOne="Where spiders roam in caves within Elwynn Forest, adventurers have been known to become poisoned and diseased. Find a Wounded Aventurer and Purify them, and they may teach you something new in return."
      runeTwoRumorRaceOne="Throughout the red mountains near Elwynn Forest, a Blasphemous orc has been known to spread his vile taint. Defeat him to learn this ability."
      runeThreeRumorRaceOne="Upon defeating foes, you may stumble upon unfinished crates that can be returned to the Azeroth Commerce Authority either empty or filled with goods. Become Friends with these people and they may reveal some new skills to you."
      runeFourRumorRaceOne="Once you're strong enough to learn new abilities, go have a word with your trainer for the first time! They might have something to show you."
      runeFiveRumorRaceOne="A goblin in Ratchet has hoarded a great many runes, and he has one for you as well. In order to retrieve it, you must complete the tasks he gives you, and provide to him the items he seeks."
      runeSixRumorRaceOne="There is a dangerous tower hidden away in Darkshore, where foul warlocks gather to cast powerful magic. These warlocks possess an orb of great evil. Claim it, and find a purifier along the road to Ashenvale that might help you quell the evil magic within. Follow his instructions and once you turn to the Warlocks of Stormwind for assistance, travel to the site of Mannoroth's destruction and slay the demons there until you have enough essence to destroy the orb upon his fallen weapons."
      runeSevenRumorRaceOne="In the wicked forests of Duskwood, the Defias Brotherhood have gathered up holy librams for their nefarious purposes. Reclaim one from them and follow its instructions to unlock the power within."
      runeEightRumorRaceOne="A wicked, undead member of the Defias is rumored to lurk near the southeastern border to Duskwood in Westfall. Defeat them and claim the Libram they carry to unlock new powers."
      runeNineRumorRaceOne="Inside the northern and western Defias mines of Westfall, an eternal skeletal worker has appeared carrying a Libram of power. Defeat them with holy power to reclaim it."
      runeTenRumorRaceOne="East of the southern docks of Elwynn Forest where smuggling is known to occur, a fallen adventurer restlessly awaits their last rites. Bring a healing friend and give these to the corpse to receive its knowledge."
      runeElevenRumorRaceOne="Inside the city of Stormwind, within the Park, a local bartender has a position for a bouncer available, with the promise of a reward if one accepts the role."
      runeTwelveRumorRaceOne="A member of the Stormwind Cathedral has gone missing and has left no word of their location. Investigate the catacombs beneath the church for a clue to where she might be."
      runeOneRumorRaceTwo="Where leprosy roams near a former city within Dun Morogh, adventurers have been known to become poisoned and diseased. Find a Wounded Aventurer and Purify them, and they may teach you something new in return."
      runeTwoRumorRaceTwo="Throughout the red mountains near Elwynn Forest, a Blasphemous orc has been known to spread his vile taint. Defeat him to learn this ability."
      runeThreeRumorRaceTwo="Upon defeating foes, you may stumble upon unfinished crates that can be returned to the Azeroth Commerce Authority either empty or filled with goods. Become Friends with these people and they may reveal some new skills to you."
      runeFourRumorRaceTwo="Once you're strong enough to learn new abilities, go have a word with your trainer for the first time! They might have something to show you."
      runeFiveRumorRaceTwo="A goblin in Ratchet has hoarded a great many runes, and he has one for you as well. In order to retrieve it, you must complete the tasks he gives you, and provide to him the items he seeks."
      runeSixRumorRaceTwo="There is a dangerous tower hidden away in Darkshore, where foul warlocks gather to cast powerful magic. These warlocks possess an orb of great evil. Claim it, and find a purifier along the road to Ashenvale that might help you quell the evil magic within. Follow his instructions and once you turn to the Warlocks of Stormwind for assistance, travel to the site of Mannoroth's destruction and slay the demons there until you have enough essence to destroy the orb upon his fallen weapons."
      runeSevenRumorRaceTwo="In the wicked forests of Duskwood, the Defias Brotherhood have gathered up holy librams for their nefarious purposes. Reclaim one from them and follow its instructions to unlock the power within."
      runeEightRumorRaceTwo="Inside a cave filled with Troggs in Loch Modan, a reliquary is rumored to have sunk beneath the pools. Inside, a Libram is said to contain great power if its contents can be deciphered."
      runeNineRumorRaceTwo="A retinue of paladins recently passed through Thelsamar in Loch Modan and spent a night at the inn. When they left, a Libram remained in one of the lower rooms, only reclaimable by a paladin."
      runeTenRumorRaceTwo="Down the hills and to the west of Kharanos in Dun Morogh, a cave of wendigo's sits. Inside, a fallen adventurer restlessly awaits their last rites. Bring a healing friend and give these to the corpse to receive its knowledge."
      runeElevenRumorRaceTwo="Inside the city of Stormwind, within the Park, a local bartender has a position for a bouncer available, with the promise of a reward if one accepts the role."
      runeTwelveRumorRaceTwo="A member of the Stormwind Cathedral has gone missing and has left no word of their location. Investigate the catacombs beneath the church for a clue to where she might be."
      raceOneImage="/wow-icons/character_human_male.webp"
      raceTwoImage="/wow-icons/character_dwarf_male.webp"
      runeOneImage="/wow-icons/paladin-runes/aegis.webp"
      runeTwoImage="/wow-icons/paladin-runes/avengers_shield.webp"
      runeThreeImage="/wow-icons/paladin-runes/beacon_of_light.webp"
      runeFourImage="/wow-icons/paladin-runes/crusader_strike.webp"
      runeFiveImage="/wow-icons/paladin-runes/divine_sacrifice.webp"
      runeSixImage="/wow-icons/paladin-runes/divine_storm.webp"
      runeSevenImage="/wow-icons/paladin-runes/exorcist.webp"
      runeEightImage="/wow-icons/paladin-runes/hand_of_reckoning.webp"
      runeNineImage="/wow-icons/paladin-runes/horn_of_lordaeron.webp"
      runeTenImage="/wow-icons/paladin-runes/inspiration_exemplar.webp"
      runeElevenImage="/wow-icons/paladin-runes/rebuke.webp"
      runeTwelveImage="/wow-icons/paladin-runes/seal_of_martyrdom.webp"
    />
  );
}
