"use client";

import styles from "./page.module.scss";
import Sorting from "../components/Sorting";

export default function DruidPage() {
  return (
    <Sorting
      class="Druid"
      zoneOneRaceOne="Teldrassil"
      zoneOneRaceTwo="Mulgore"
      zoneOneCityRaceOne="Darnassus"
      zoneOneCityRaceTwo="Thunder Bluff"
      zoneTwoRaceOne="Darkshore"
      zoneTwoRaceTwo="The Barrens"
      infoStarterZoneFirstRune="Once you're strong enough to learn new abilities, go have a word with your trainer for the first time! They might have something to show you."
      infoStarterZoneSecondRuneRaceOne="New flowers have sprouted across Teldrassil. Keep an eye out for what they might rouse from slumber!"
      infoStarterZoneSecondRuneRaceTwo="New flowers have sprouted across Mulgore. Keep an eye out for what they might rouse from slumber!"
      infoStarterZoneThirdRuneRaceOne="The spirit of a deceased adventurer has been heard tale of to the north outside of Darnassus. It it said that another adventurer with healing powers alongside yourself can bring their spirit to rest."
      infoStarterZoneThirdRuneRaceTwo="The spirit of a deceased adventurer has been heard tale of to the far east of Thunder Bluff. It it said that another adventurer with healing powers alongside yourself can bring their spirit to rest."
      infoStarterZoneFourthRuneRaceOne="Three white stones have appeared in XX inside Teldrassil. They call to Elune. Make sure to use your abilities to answer."
      infoStarterZoneFourthRuneRaceTwo="Three white stones have appeared in XX inside Mulgore. They call to Mu'sha. Make sure to use your abilities to answer."
      infoCitiesRaceOne="No rumors of any runes inside cities exist for you!"
      infoCitiesRaceTwo="No rumors of any runes inside cities exist for you!"
      infoSecondZone="Sometimes idols have been known to enable your growth! Search for ferocious idols held by XX!"
      infoThirdZone="Hidden away in the wet marshes of the east, mushrooms can be found in caves: or on those that collect such things. It is said that ingesting these mushrooms allow you to talk to all manner of creatures, even those amphibious frogs."
      infoSecretZone="Wild begets wild. Members of the same druidic species as those that serve the Horde are rumored to hold something that might assist you, but these druids are not part of the Horde and have been said to lurk around the Stoney Mountains of the West."
      runeOne="Fury of Stormrage"
      runeTwo="Living Seed"
      runeThree="Lacerate"
      runeFour="Lifebloom"
      runeFive="Mangle"
      runeSix="Savage Roar"
      runeSeven="Skull Bash"
      runeEight="Starsurge"
      runeNine="Sunfire"
      runeTen="Survival of the Fittest"
      runeEleven="Wild Growth"
      runeTwelve="Wild Strikes"
      runeOneRumor="Once you're strong enough to learn new abilities, go have a word with your trainer for the first time! They might have something to show you."
      runeTwoRumorRaceOne="New flowers have sprouted across Teldrassil. Keep an eye out for what they might rouse from slumber!"
      runeThreeRumorRaceOne="The aquatic life of Loch Modan can be quite hungry! Perhaps the fisherman's wife has something that might feed them? Alternatively, perhaps the aquatic life of Darkshore is equally hungry? They seem to have a preference for crab treats, especially those that the Furbolg are keen for."
      runeFourRumorRaceOne="The spirit of a deceased adventurer has been heard tale of to the north outside of Darnassus. It it said that another adventurer with healing powers alongside yourself can bring their spirit to rest."
      runeFiveRumorRaceOne="To channel the power of your claws and to gain the ability to mangle your foes, certain important furbolgs in Teldrassil have been known to carry the same ability. Channel your Rage to grow the power of your Claw."
      runeSixRumorRaceOne="In Darkshore, a strong mother is said to guard an idol that can help you channel this strength. ADD LOCH MODAN. In Westfall, Gnolls carry this same idol."
      runeSevenRumorRaceOne="Upon defeating foes, you may stumble upon unfinished crates that can be returned to the Azeroth Commerce Authority either empty or filled with goods. Become Friends with these people and they may reveal some new skills to you."
      runeEightRumorRaceOne="Hidden away in the wet marshes of the east, mushrooms can be found in caves: or on those that collect such things. It is said that ingesting these mushrooms allow you to talk to all manner of creatures, even those amphibious frogs."
      runeNineRumorRaceOne="Three white stones have appeared in XX inside Teldrassil. They call to Elune. Make sure to use your abilities to answer."
      runeTenRumorRaceOne="A goblin in Ratchet has hoarded a great many runes, and he has one for you as well. In order to retrieve it, you must complete the tasks he gives you, and provide to him the items he seeks."
      runeElevenRumorRaceOne="In a land dear to all druids, you will find a Night Elf that offers you a new task to complete, taking you all over Azeroth. Finish this task for your reward."
      runeTwelveRumorRaceOne="Wild begets wild. Members of the same druidic species as those that serve the Horde are rumored to hold something that might assist you, but these druids are not part of the Horde and have been said to lurk around the Stoney Mountains of the West."
      runeTwoRumorRaceTwo="New flowers have sprouted across Mulgore. Keep an eye out for what they might rouse from slumber!"
      runeThreeRumorRaceTwo="Thanks to the centaurs overtaking a forgotten oasis, a couple of Snapjaws have been forced to relocate to another pair of pools. Unfortunately, their eggs were left behind! Perhaps they would be grateful to get them back."
      runeFourRumorRaceTwo="The spirit of a deceased adventurer has been heard tale of to the far east of Thunder Bluff. It it said that another adventurer with healing powers alongside yourself can bring their spirit to rest."
      runeFiveRumorRaceTwo="To channel the power of your claws, hunt beasts of nature in Mulgore that possess similar traits and abilities to that which you desire."
      runeSixRumorRaceTwo="In the Barrens, the vicious centaur are known for hoarding great treasures in their collected Booty. Find a key and use it to gain new power."
      runeSevenRumorRaceTwo="Upon defeating foes, you may stumble upon unfinished crates that can be returned to Durotar Supply and Logistics either empty or filled with goods. Become Friends with these people and they may reveal some new skills to you."
      runeEightRumorRaceTwo="Hidden away in the wet marshes of the east, mushrooms can be found in caves: or on those that collect such things. It is said that ingesting these mushrooms allow you to talk to all manner of creatures, even those amphibious frogs."
      runeNineRumorRaceTwo="Three white stones have appeared in XX inside Mulgore. They call to Mu'sha. Make sure to use your abilities to answer."
      runeTenRumorRaceTwo="A goblin in Ratchet has hoarded a great many runes, and he has one for you as well. In order to retrieve it, you must complete the tasks he gives you, and provide to him the items he seeks."
      runeElevenRumorRaceTwo="In a land dear to all druids, you will find a Night Elf that offers you a new task to complete, taking you all over Azeroth. Finish this task for your reward."
      runeTwelveRumorRaceTwo="Wild begets wild. Members of the same druidic species as those that serve the Horde are rumored to hold something that might assist you, but these druids are not part of the Horde and have been said to lurk around the Stoney Mountains of the West."
      raceOneImage="/wow-icons/character_nightelf_female.webp"
      raceTwoImage="/wow-icons/character_tauren_male.webp"
      runeOneImage="/wow-icons/druid-runes/fury_of_stormrage.webp"
      runeTwoImage="/wow-icons/druid-runes/living_seed.webp"
      runeThreeImage="/wow-icons/druid-runes/lacerate.webp"
      runeFourImage="/wow-icons/druid-runes/lifebloom.webp"
      runeFiveImage="/wow-icons/druid-runes/mangle.webp"
      runeSixImage="/wow-icons/druid-runes/savage_roar.webp"
      runeSevenImage="/wow-icons/druid-runes/skull_bash.webp"
      runeEightImage="/wow-icons/druid-runes/starsurge.webp"
      runeNineImage="/wow-icons/druid-runes/sunfire.webp"
      runeTenImage="/wow-icons/druid-runes/survival_of_the_fittest.webp"
      runeElevenImage="/wow-icons/druid-runes/wild_growth.webp"
      runeTwelveImage="/wow-icons/druid-runes/wild_strikes.webp"
    />
  );
}
