"use client";

import styles from "./page.module.scss";
import Sorting from "../components/Sorting";

export default function DruidPage() {
  return (
    <Sorting
      class="Druid"
      zoneOneRaceOne="Teldrassil"
      zoneOneRaceTwo="Mulgore"
      zoneOneCityRaceOne="Darnassus"
      zoneOneCityRaceTwo="Thunder Bluff"
      zoneTwoRaceOne="Darkshore"
      zoneTwoRaceTwo="The Barrens"
      infoStarterZoneFirstRune="Once you're strong enough to learn new abilities, go have a word with your trainer for the first time! They might have something to show you."
      infoStarterZoneSecondRuneRaceOne="New flowers have sprouted across Teldrassil. Keep an eye out for what they might rouse from slumber!"
      infoStarterZoneSecondRuneRaceTwo="New flowers have sprouted across Mulgore. Keep an eye out for what they might rouse from slumber!"
      infoStarterZoneThirdRuneRaceOne="The spirit of a deceased adventurer like you has been heard tale of to the north outside of Darnassus. It it said that another adventurer with healing powers alongside yourself can bring their spirit to rest."
      infoStarterZoneThirdRuneRaceTwo="The spirit of a deceased adventurer has been heard tale of to the far east of Thunder Bluff. It it said that another adventurer with healing powers alongside yourself can bring their spirit to rest."
      infoStarterZoneFourthRuneRaceOne="Three white stones have appeared in XX inside Teldrassil. They call to Elune. Make sure to use your abilities to answer."
      infoStarterZoneFourthRuneRaceTwo="Three white stones have appeared in XX inside Mulgore. They call to Mu'sha. Make sure to use your abilities to answer."
      infoCitiesRaceOne="No rumors of any runes inside cities exist for you!"
      infoCitiesRaceTwo="No rumors of any runes inside cities exist for you!"
      infoSecondZone="Sometimes idols have been known to enable your growth! Search for ferocious idols held by XX!"
      infoThirdZone="Hidden away in the wet marshes of the east, mushrooms can be found in caves: or on those that collect such things. It is said that ingesting these mushrooms allow you to talk to all manner of creatures, even those amphibious frogs."
      infoSecretZone="Wild begets wild. Members of the same druidic species as those that serve the Horde are rumored to hold something that might assist you, but these druids are not part of the Horde and have been said to lurk around the Stoney Mountains of the West."
      runeOne="Fury of Stormrage"
      runeTwo="Living Seed"
      runeThree="Lacerate"
      runeFour="Lifebloom"
      runeFive="Mangle"
      runeSix="Savage Roar"
      runeSeven="Skull Bash"
      runeEight="Starsurge"
      runeNine="Sunfire"
      runeTen="Survival of the Fittest"
      runeEleven="Wild Growth"
      runeTwelve="Wild Strikes"
      runeOneRumor="Once you're strong enough to learn new abilities, go have a word with your trainer for the first time! They might have something to show you."
      runeTwoRumorRaceOne="New flowers have sprouted across Teldrassil. Keep an eye out for what they might rouse from slumber!"
      runeThreeRumorRaceOne="The aquatic life of Loch Modan can be quite hungry! Perhaps the fisherman's wife has something that might feed them? Alternatively, perhaps the aquatic life of Darkshore is equally hungry? They seem to have a preference for crab treats, especially those that the Furbolg are keen for."
      runeFourRumorRaceOne=""
      runeFiveRumorRaceOne=""
      runeSixRumorRaceOne=""
      runeSevenRumorRaceOne=""
      runeEightRumorRaceOne=""
      runeNineRumorRaceOne=""
      runeTenRumorRaceOne=""
      runeElevenRumorRaceOne=""
      runeTwelveRumorRaceOne=""
      runeTwoRumorRaceTwo="New flowers have sprouted across Mulgore. Keep an eye out for what they might rouse from slumber!"
      runeThreeRumorRaceTwo="Thanks to the centaurs overtaking a forgotten oasis, a couple of Snapjaws have been forced to relocate to another pair of pools. Unfortunately, their eggs were left behind! Perhaps they would be grateful to get them back."
      runeFourRumorRaceTwo=""
      runeFiveRumorRaceTwo=""
      runeSixRumorRaceTwo=""
      runeSevenRumorRaceTwo=""
      runeEightRumorRaceTwo=""
      runeNineRumorRaceTwo=""
      runeTenRumorRaceTwo=""
      runeElevenRumorRaceTwo=""
      runeTwelveRumorRaceTwo=""
      raceOneImage="/wow-icons/character_nightelf_female.webp"
      raceTwoImage="/wow-icons/character_tauren_male.webp"
    />
  );
}
